name: Build OpenWrt Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
            target: armsr/armv8
            sdk_url: https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv8/openwrt-sdk-23.05.5-armsr-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1  # 修正：指定具体版本号

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            ecj \
            fastjar \
            file \
            g++ \
            gawk \
            gettext \
            git \
            java-propose-classpath \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            python3 \
            python3-dev \
            python3-setuptools \
            rsync \
            subversion \
            swig \
            time \
            unzip \
            wget \
            xsltproc \
            zlib1g-dev

      - name: Setup OpenWrt SDK
        run: |
          SDK_FILE="openwrt-sdk-23.05.5-armsr-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget ${{ matrix.sdk_url }}
          echo "Current directory contents:"
          ls -la
          echo "Extracting SDK..."
          tar xf "$SDK_FILE"
          echo "After extraction, directory contents:"
          ls -la
          SDK_DIR="openwrt-sdk-23.05.5-armsr-armv8_gcc-12.3.0_musl.Linux-x86_64"
          if [ ! -d "$SDK_DIR" ]; then
            echo "ERROR: SDK directory '$SDK_DIR' not found!"
            exit 1
          fi
          echo "Found SDK directory: $SDK_DIR"
          mv "$SDK_DIR" sdk

      - name: Setup package
        run: |
          cd sdk
          # 配置 feeds
          cat > feeds.conf.default << EOF
          src-git base https://git.openwrt.org/openwrt/openwrt.git
          src-git packages https://git.openwrt.org/feed/packages.git
          src-git luci https://git.openwrt.org/project/luci.git
          src-git routing https://git.openwrt.org/feed/routing.git
          src-git telephony https://git.openwrt.org/feed/telephony.git
          EOF
          
          # 更新所有 feeds
          ./scripts/feeds update -a
          
          # 先安装基础包
          ./scripts/feeds install -a -p base
          
          # 然后安装其他 feeds
          ./scripts/feeds install -a -p packages
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install -a -p routing
          ./scripts/feeds install -a -p telephony
          
          # 特别确保安装关键包
          ./scripts/feeds install zlib
          ./scripts/feeds install libiconv-full
          ./scripts/feeds install libintl-full
          ./scripts/feeds install libpcre2
          ./scripts/feeds install libncurses
          ./scripts/feeds install libreadline
          ./scripts/feeds install golang
          
          # 设置我们的包
          mkdir -p package/writefreely
          cp -r ../writefreely/* package/writefreely/

      - name: Build package
        run: |
          cd sdk
          make defconfig
          make package/writefreely/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # 同时更新 upload-artifact 的版本
        with:
          name: writefreely-ipk
          path: sdk/bin/packages/*/base/writefreely_*.ipk
