name: Build OpenWrt Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm_cortex-a7
          - arm_cortex-a9
          - aarch64_generic
        include:
          - arch: x86_64
            target: x86/64
            sdk_url: https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          - arch: arm_cortex-a7
            target: sunxi/cortexa7
            sdk_url: https://downloads.openwrt.org/releases/22.03.5/targets/sunxi/cortexa7/openwrt-sdk-22.03.5-sunxi-cortexa7_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
          - arch: arm_cortex-a9
            target: mvebu/cortexa9
            sdk_url: https://downloads.openwrt.org/releases/22.03.5/targets/mvebu/cortexa9/openwrt-sdk-22.03.5-mvebu-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
          - arch: aarch64_generic
            target: armvirt/64
            sdk_url: https://downloads.openwrt.org/releases/22.03.5/targets/armvirt/64/openwrt-sdk-22.03.5-armvirt-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            ecj \
            fastjar \
            file \
            g++ \
            gawk \
            gettext \
            git \
            java-propose-classpath \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            python3 \
            python3-dev \
            python3-setuptools \
            rsync \
            subversion \
            swig \
            time \
            unzip \
            wget \
            xsltproc \
            zlib1g-dev

      - name: Setup OpenWrt SDK
        run: |
          wget "${{ matrix.sdk_url }}"
          tar xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Update feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Setup package
        run: |
          cd sdk
          mkdir -p package/writefreely
