name: Build OpenWrt Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm_cortex-a7
          - arm_cortex-a9
          - aarch64_generic
        include:
          - arch: x86_64
            target: x86/64
            sdk_url: https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.
